package com.shubhi.dependencytest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class data_objet implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public data_objet() {
    }




}